datasets:
    LibriSpeech:
        root: /remote-home1/share/data/SpeechPretrain/librispeech/LibriSpeech/
        trainsets: ['train-clean-100','train-clean-360','train-other-500']
        valsets: ['test-clean']
        testsets: ['test-clean']
view:
    train_filelist: ./filelists/librispeech_train.txt
    val_filelist: ./filelists/librispeech_val.txt
    test_filelist: ./filelists/librispeech_test.txt
audio:
  sr: 16000
  normalization: False
  max_wav_value: 32768.0
stft:
  n_fft: 1280
  window_length: 1280
  hop_length: 320
